### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by Sukistar** [matthew-robertson/vore-tracker#14]
Is it currently offline for some reason? Should I be able to tell why?

**Comment by matthew-robertson** [comment]
You can tell if it's offline if it isn't listed as being online on your server. I haven't set up an status webpage or anything like that (yet?).

It does seem to be down, and unintentionally so. Unfortunately, I likely won't be able to fix it today.

**Comment by Sukistar** [comment]
Thanks for letting me know!

**Comment by matthew-robertson** [comment]
Should be back up now. Seems to be an issue with Discord resetting the bot's connection after it's been running for a while. Reopening this to remind me to figure out some way to fix this.

**Comment by matthew-robertson** [comment]
Thanks for letting me know. Tonight I should be able to look into this, and hopefully fix it for good.

**Comment by SartoRiccardo** [comment]
It's offline again

**Comment by matthew-robertson** [comment]
I'm not sure if the underlying issue is a Discord.py issue or a Discord issue, but hopefully we should be able to get around it now by just reconnecting once the connection is dropped.
