### ISSUE TITLE
Changing text properties bypasses Vore Tracker

### ISSUE THREAD

**Issue by SartoRiccardo** [matthew-robertson/vore-tracker#15]
Saying, for example, _V_**o**re doesn't give a warning.

This is because `message.content` actually returns `_V_**o**re` and not just `Vore`.

**Comment by SartoRiccardo** [comment]
Also, the filter is easy to bypass with cyrillic characters, since the letters e and o look the same as their latin counterparts but are still technically different characters

**Comment by matthew-robertson** [comment]
I've just completed a fix for this. It's a little band-aid-y but should be live once I get something in for all the other issues.
