### ISSUE TITLE
Set up an actual Database

### ISSUE THREAD

**Issue by matthew-robertson** [matthew-robertson/vore-tracker#19]
At this point we're starting to track a decent amount of state. It'd probably make more sense to start storing this in an actual database, instead of the awful "save file" format I've been using. 

As a benefit of this, we can start tracking more stats. Including, but not limited to: how many times the bot has been triggered per server, what individual users are the worst repeat offenders, average time between triggers, server add date, etc...

**Comment by woodgern** [comment]
https://github.com/matthew-robertson/vore-tracker/pull/23
