### ISSUE TITLE
Create a support Discord server

### ISSUE THREAD

**Issue by SartoRiccardo** [matthew-robertson/vore-tracker#21]
A Discord server dedicated to your bot (and eventually future ones) could help the users communicate with you, and you could easily broadcast announcements (such as the big update you're planning to make)

**Comment by matthew-robertson** [comment]
A server has been created. It's barebones as hell, but here you go: https://discord.gg/nUZsfYS

Hopefully I haven't mis-configured anything, but I guess we'll find out.
